Informatievlaanderen/VSDS-Linked-Data-Interactions

ldi-api/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/config/InputComponentDefinition.java, ldi-nifi.Dockerfile, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/pom.xml, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/NgsiV2ToLdProcessor.java, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/config/NgsiV2ToLdProcessorProperties.java, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/NgsiV2ToLdProcessorTest.java, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/test/resources/mappings/ngsi-ld-core-context.json, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/test/resources/mappings/water-quality-observed-context.json, ldi-nifi/ldi-nifi-processors/ngsiv2-to-ld-processor/src/test/resources/ngsiV2_wqo_input.json, ldi-nifi/ldi-nifi-processors/pom.xml, ldi-orchestrator/ldio-application/pom.xml, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/FlowAutoConfiguration.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/OrchestratorConfig.java, ldi-orchestrator/ldio-application/src/test/resources/application-test.yml, ldi-orchestrator/ldio-connectors/ldio-ngsiv2-to-ld-adapter/pom.xml, ldi-orchestrator/ldio-connectors/ldio-ngsiv2-to-ld-adapter/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/LdioNgsiv2ToLdAdapterAutoConfig.java, ldi-orchestrator/ldio-connectors/pom.xml, ldio.Dockerfile
* Nifi implementation
* Nifi docker
* LDIO docker
=> feat: VSDSPUB-288: Finishing NGSIV2toLd

ldi-core/version-object-creator/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/LdesMemberConverterTest.java
The test would fail if it was run the last second of a minute
=> Fix unreliable test

ldi-core/rml-adapter/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/RmlAdapter.java, ldi-core/rml-adapter/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/functions/LDI.java, ldi-core/rml-adapter/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/functions/TimeFunctions.java, ldi-core/rml-adapter/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/functions/TimeFunctionsTest.java
=> feat: Included RML function for translation from EPOC to ISO 8601 date formats

ldi-orchestrator/ldio-application/pom.xml, ldi-orchestrator/ldio-connectors/ldio-azure-blob-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdiAzureBlobOut.java, ldi-orchestrator/ldio-connectors/ldio-azure-blob-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/conversionstrategy/json/Model2JsonConverter.java, ldio.Dockerfile
Include the LdioAzureBlobOut connector in LDIO docker image.
(and change upload from InputStream to BinaryData (for non-ascii characters))
=> Feature: Include LdioAzureBlobOut connector in LDIO docker image

ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/exception/CreateDirectoryFailedException.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/sqlite/EntityManagerFactory.java, ldi-core/ldes-client/tree-node-supplier/src/main/resources/META-INF/persistence.xml
Create a separate directory for the sqlite db and remove when database is deleted.
=> Feature: sqlite db in separate directory

ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/domain/services/MemberRepositoryFactory.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/domain/services/TreeNodeRecordRepositoryFactory.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/domain/valueobject/StatePersistenceStrategy.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/FileBasedMemberRepository.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/FileBasedTreeNodeRecordRepository.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/FileManager.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/FileManagerFactory.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/exception/CreateDirectoryFailedException.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/exception/DestroyStateFailedException.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/exception/StateOperationFailedException.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/mapper/MemberRecordMapper.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/filebased/mapper/TreeNodeRecordMapper.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/sqlite/EntityManagerFactory.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/repository/sqlite/exception/DestroyDbFailedException.java, ldi-core/ldes-client/tree-node-supplier/src/test/java/ldes/client/treenodesupplier/MemberSupplierSteps.java, ldi-core/ldes-client/tree-node-supplier/src/test/resources/features/member-supplier.feature, ldi-core/ldes-client/tree-node-supplier/src/test/resources/features/restart-client.feature, ldi-orchestrator/ldio-connectors/ldio-azure-blob-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/BlobClientFactory.java, ldi-orchestrator/ldio-connectors/ldio-azure-blob-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdiAzureBlobOut.java
File-based persistence implementation for the LDES Client
=> Feat/vsdspub 803/file based state

ldio.Dockerfile
This reverts commit 2bf37b54cfc2be8e4e10dc2ec1452cccd1681791.
=> Revert "temp: run as root user"

docs/_ldio/index.md, ldi-api/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/types/LdiAdapter.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/AdapterDebugger.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/FlowAutoConfiguration.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/OutputDebugger.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/TransformDebugger.java, ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/OrchestratorConfig.java
To be merged after sprint change.
=> Feat: LDIO component debug logger

ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/MemberSupplier.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/TreeNodeProcessor.java, ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/domain/valueobject/EndOfLdesException.java, ldi-core/ldes-client/tree-node-supplier/src/test/java/ldes/client/treenodesupplier/MemberSupplierTest.java, ldi-nifi/ldi-nifi-processors/ldes-client-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/LdesClient.java, ldi-nifi/ldi-nifi-processors/ldes-client-processor/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/LdesClientTest.java, ldi-nifi/ldi-nifi-processors/ldes-client-processor/src/test/resources/mappings/end-of-ldes.json, ldi-orchestrator/ldio-connectors/ldio-ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdesClientRunner.java
Fix for issue https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/305
=> Feat: End LDES client gracefully

ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/valueobjects/ComponentProperties.java, ldi-orchestrator/ldio-common/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/valueobjects/ComponentPropertiesTest.java, ldi-orchestrator/ldio-connectors/ldio-http-in-poller/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/HttpInputPoller.java, ldi-orchestrator/ldio-connectors/ldio-http-in-poller/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/HttpInputPollerAutoConfig.java, ldi-orchestrator/ldio-connectors/ldio-http-in-poller/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/HttpInputPollerTest.java
Fix for https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/304
=> Feat: Add support for multiple urls in the http poller

ldi-core/file-archiving/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/FileName.java, ldi-core/file-archiving/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/TimestampExtractor.java, ldi-core/file-archiving/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/TimestampFromCurrentTimeExtractor.java, ldi-core/file-archiving/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/TimestampFromPathExtractor.java, ldi-core/file-archiving/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/TimestampFromCurrentTimeExtractorTest.java, ldi-core/file-archiving/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/TimestampFromPathExtractorTest.java, ldi-core/file-archiving/src/test/resources/model-with-timestamp20220520.nq, ldi-nifi/ldi-nifi-processors/archive-file-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/ArchiveFileOutProcessor.java, ldi-nifi/ldi-nifi-processors/archive-file-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/config/ArchiveFileOutProperties.java, ldi-nifi/ldi-nifi-processors/archive-file-out/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/ArchiveFileOutProcessorTest.java, ldi-orchestrator/ldio-connectors/ldio-file-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioFileOut.java, ldi-orchestrator/ldio-connectors/ldio-file-out/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/LdioFileOutAutoConfig.java, ldi-orchestrator/ldio-connectors/ldio-file-out/src/test/resources/features/file-out-it.feature
Fixes:
- https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/274
- https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/250
=> Fix: make timestamp in archive out component optional and use ttl

ldi-core/version-object-creator/pom.xml, ldi-core/version-object-creator/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/VersionObjectCreator.java, ldi-core/version-object-creator/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/VersionObjectCreatorTest.java, ldi-nifi/ldi-nifi-processors/create-version-object-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/CreateVersionObjectProcessor.java, ldi-nifi/ldi-nifi-processors/create-version-object-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/config/CreateVersionObjectProcessorRelationships.java, ldi-nifi/ldi-nifi-processors/create-version-object-processor/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/CreateVersionObjectProcessorTest.java, pom.xml
#388 github-issue
avoid throwing exception on creation failure,
log warning with detail instead
=> feat: version object creator: remove thrown exception

ldi-nifi/ldi-nifi-processors/sparql-interactions-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/repository/SparqlSelectService.java, ldi-nifi/ldi-nifi-processors/sparql-interactions-processor/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/SparqlSelectProcessorTest.java, ldi-nifi/ldi-nifi-processors/sparql-interactions-processor/src/test/resources/output_select_success_1.json, ldi-nifi/ldi-nifi-processors/sparql-interactions-processor/src/test/resources/people_data.nq
=> fix: #422 : Return correct datatypes in JSON structure of SPARQL select result

ldi-nifi.Dockerfile, ldio.Dockerfile
=> fix: deprecated docker base image open jdk 18

ldi-orchestrator/ldio-connectors/ldio-ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioLdesClient.java
Init phase of client connector prevented pipeline to be registered
=> fix: blocked client connector

ldi-core/request-executor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/requestexecutor/executor/edc/services/MemoryTokenService.java, ldi-core/request-executor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/requestexecutor/executor/edc/services/MemoryTokenServiceLifecycle.java, ldi-core/request-executor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/requestexecutor/executor/edc/services/TokenService.java, ldi-core/request-executor/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldi/requestexecutor/executor/edc/services/MemoryTokenServiceTest.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/services/PipelineStatusService.java, ldi-orchestrator/ldio-application/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/modules/DummyIn.java, ldi-orchestrator/ldio-application/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/services/PipelineStatusServiceTest.java, ldi-orchestrator/ldio-application/src/test/resources/features/management.feature, ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/types/LdioInput.java, ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/valueobjects/PipelineStatusTrigger.java, ldi-orchestrator/ldio-connectors/ldio-amqp/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioAmqpIn.java, ldi-orchestrator/ldio-connectors/ldio-amqp/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/AmqpInIntegrationTestSteps.java, ldi-orchestrator/ldio-connectors/ldio-archive-file-in/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioArchiveFileIn.java, ldi-orchestrator/ldio-connectors/ldio-http-in-poller/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/LdioHttpInputPollerAutoConfig.java, ldi-orchestrator/ldio-connectors/ldio-http-in/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/LdioHttpInAutoConfig.java, ldi-orchestrator/ldio-connectors/ldio-http-in/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioHttpInputTest.java, ldi-orchestrator/ldio-connectors/ldio-kafka/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioKafkaIn.java, ldi-orchestrator/ldio-connectors/ldio-kafka/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/KafkaInIntegrationTestSteps.java, ldi-orchestrator/ldio-connectors/ldio-ldes-client-connector/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioLdesClientConnectorApi.java, ldi-orchestrator/ldio-connectors/ldio-ldes-client-connector/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioLdesClientConnectorApiController.java, ldi-orchestrator/ldio-connectors/ldio-ldes-client-connector/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/LdioLdesClientConnectorAutoConfig.java, ldi-orchestrator/ldio-connectors/ldio-ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioLdesClient.java
Fixes pipeline statuses having double function and fixes https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/524
=> fix: separate ldio status from triggers

docs/_ldio/examples/index.md, docs/_ldio/index.md
Moved the Docker Compose section from the examples index page to the LDIO index page with some extended documentation.
=> feat: VSDSPUB-1296: document how to start up LDIO container

docs/_ldio/ldio-inputs/ldio-ldes-client.md
Modifying the LDES Client GitHub page.
=> docs: VSDSPUB-1293 - LDIO LDES Client Config

ldi-core/ldes-client/tree-node-supplier/src/main/java/ldes/client/treenodesupplier/TreeNodeProcessor.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/PipelineServiceImpl.java, ldi-orchestrator/ldio-application/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/web/PipelineExceptionHandler.java, ldi-orchestrator/ldio-application/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/PipelineServiceTest.java, ldi-orchestrator/ldio-application/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/web/PipelineControllerTest.java, ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/creation/LdioInput.java, ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/exception/PipelineException.java, ldi-orchestrator/ldio-common/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/pipeline/exception/PipelineInitialisationException.java, ldi-orchestrator/ldio-connectors/ldio-ldes-client/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioLdesClient.java, ldi-orchestrator/ldio-connectors/ldio-ldes-client/src/test/java/be/vlaanderen/informatievlaanderen/ldes/ldio/LdioLdesClientTest.java
* Unable to restart LDES Client when endpoint was previously unavailable
* Gracefully shutdown LDES Client (wait for pipeline Data IN == Data OUT)
=> fix: LDIO Ldes Client improvements

ldi-orchestrator/ldio-connectors/ldio-change-detection-filter/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/HashedStateMemberRepositoryFactory.java, ldi-orchestrator/ldio-connectors/ldio-change-detection-filter/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldio/config/LdioChangeDetectionFilterAutoConfig.java
The class with name `HasedStateMemberRepositoryFactory` should be 'HashedStateMemberRepositoryFactory'
=> chore: resolved typo
